Add auth system
Nasz-Elektryk/SPITO-backend pull request #5
Opened 2023-10-14 17:57 UTC by maxidragon

Closes #1

2023-10-14 18:49 UTC, maxidragon commented
I don't know why the tests are failing, any ideas? Everything is working locally

2023-10-15 15:04 UTC, BaderBC requested changes
LGTM, just fix issues which I mentioned and merge

2023-10-15 15:04 UTC, BaderBC commented on src/auth/strategy/jwt.strategy.ts
delete console.logs

2023-10-15 15:09 UTC, BaderBC approved these changes

2023-10-15 15:10 UTC, merged